apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pb1kjhglc-go
  janus-idp.io/tekton: pb1kjhglc-go
  backstage.io/kubernetes-id: pb1kjhglc-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pb1kjhglc-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
