apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pb1kjhglc-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pb1kjhglc-go 
  name: pb1kjhglc-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: pb1kjhglc-go 
